services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.7.2
    container_name: "swagger-ui"
    ports:
      - "8000:8080"
    volumes:
      - ./specs:/REST_API
    environment:
      SWAGGER_JSON: /REST_API/openapi.yaml
